# Generated by Django 5.2.2 on 2025-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
